# Generated by Django 2.0.3 on 2018-04-02 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_institutebody_registered'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='institutebody',
            name='registered',
        ),
    ]
